### ISSUE TITLE
Any plan for Mitsuba code release?

### ISSUE THREAD

**Issue by ryushinn** [sssssy/pytorch-mitsuba-NLB_Release#1]
Hi,

Your pre-trained models are super helpful. I want to render some images using your Neural BRDF, but it seems that the rendering code (as a Mitsuba BSDF plugin, I guess) is missing in the repo. 

Do you have any plans to release your Mitsuba code? Any information on how you rendered images using your Neural BRDF will be very useful, like which renderer and version you were using, and how did you extend the renderer to support your Neural BRDF. 

I TRULY appreciate it.

**Comment by sssssy** [comment]
Hi, 

I have to clarify that the rendering is not implemented in Mitsuba, but in Pytorch. The basic idea is to perform path tracing in Mitsuba and only store the ray intersections into file buffers, and then infer the network with Pytorch to get the final rendering.

However, I believe there're better ways to do it now with some advanced codebases. For example, you can easily integrate the network inference into Mitsuba 3 with Python scripts.

Since I'm not currently working on the specific code release that you request, I'd like to close this issue for now. Thanks for your understanding.
